name: Deploy to VPS

on:
  push:
    branches:
      - main # Nếu anh/chị dùng nhánh master thì sửa main thành master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # 1. Di chuyển vào đúng thư mục chứa tệp docker-compose.yml
            cd /root/tonghanh/webapp/danhgianhanvien
            
            # 2. Lấy mã nguồn mới nhất từ GitHub
            git pull origin main
            
            # 3. Tiến hành Build lại Image và chạy nền (Zero-downtime)
            docker-compose up -d --build
